apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crushftp.fullname" . }}-configmap
  labels:
    {{- include "crushftp.labels" . | nindent 4 }}
data:
  init.sh: |-
    #!/usr/bin/env bash
    echo "ls -al var/opt/CrushFTP10-PV"
    ls -al var/opt/CrushFTP10-PV

    # Checking contents of /var/opt/CrushFTP10-PV excluding lost+found
    contents=$(ls -A /var/opt/CrushFTP10-PV | grep -v 'lost+found')

    # Checking if contents variable is empty
    if [ -z "$contents" ]; then
        echo "Directory /var/opt/CrushFTP10-PV is empty (excluding lost+found). Proceeding with copy operation."
        # Copying files from /var/opt/CrushFTP10 to /var/opt/CrushFTP10-PV
        cp -rf /var/opt/CrushFTP10/* /var/opt/CrushFTP10-PV
        echo "Copy operation completed."
    else
        echo "Directory /var/opt/CrushFTP10-PV contains files other than lost+found. Skipping copy operation."
    fi


  startup.sh: |-
    #!/usr/bin/env bash
    CRUSH_FTP_BASE_DIR="/var/opt/CrushFTP10-PV"
    rm -rf /var/opt/CrushFTP10

    if [ -z ${CRUSH_ADMIN_USER} ]; then
        CRUSH_ADMIN_USER=crushadmin
    fi

    if [ -z ${CRUSH_ADMIN_PROTOCOL} ]; then
        CRUSH_ADMIN_PROTOCOL=http
    fi

    if [ -z ${CRUSH_ADMIN_PORT} ]; then
        CRUSH_ADMIN_PORT=8080
    fi

    if [[ ! -f ${CRUSH_FTP_BASE_DIR}/admin_user_set.txt ]] ; then
        echo "Creating default admin..."
        cd ${CRUSH_FTP_BASE_DIR} && java -jar ${CRUSH_FTP_BASE_DIR}/CrushFTP.jar -a "${CRUSH_ADMIN_USER}" "${CRUSH_ADMIN_PASSWORD}"
        touch ${CRUSH_FTP_BASE_DIR}/admin_user_set.txt
    fi

    ${CRUSH_FTP_BASE_DIR}/crushftp_init.sh start

    until [ -f ${CRUSH_FTP_BASE_DIR}/settings/prefs.XML ]
    do
        sleep 1
    done

    echo "########################################"
    echo "# URL:		${CRUSH_ADMIN_PROTOCOL}://127.0.0.1:${CRUSH_ADMIN_PORT}"
    echo "# User:		${CRUSH_ADMIN_USER}"
    echo "# Password:	Check secret
    echo "# config-dir:	${CRUSH_FTP_BASE_DIR}"
    echo "########################################"

    while true; do sleep 86400; done