kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "crushftp.fullname" . }}-crush
  labels:
    {{- include "crushftp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.shared.storageClassName }}
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "crushftp.fullname" . }}-config
  labels:
    {{- include "crushftp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.shared.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.configVolume.size }}
---
